### ISSUE TITLE
read-only embedded redis db from db_file?

### ISSUE THREAD

**Issue by JayDeng2837** [yahoo/redislite#114]
Hi All,

Is there a read-only version for redis server created by passing in db_file_name?

If not, what would be the behavior if multiple instances of Redis are created by feed in db_file_name?
Would it be safe?....

also, may i ask, if multiple instances are created this way, which pid  will be logged in the pidfile?
will the last instance override previous pids? thanks

**Comment by dwighthubbard** [comment]
If multiple instances are pointed at the same db file, only the first instance will start redis, the others will connect to the running redis server.  The pidfile will be for the redis server itself.
