### ISSUE TITLE
Is it possible to use redis-cli with a running redislite?

### ISSUE THREAD

**Issue by ngoonee** [yahoo/redislite#115]
I've tried redis-cli -s /path/to/the/redislite/socket.db but it gives me 'Connection Refused'. Is this supposed to be possible? I've also tried the redis-cli binary in the redislite folder, with the same result.

**Comment by dwighthubbard** [comment]
The db file is the filename of the backing file not the name of the unix domain socket that redis is using.  Redislite has a socket_file attribute that has the full path to the socket file.  The module also includes the redis-cli binary.

Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import redislite
>>> import subprocess
>>> r = redislite.StrictRedis()
>>> subprocess.call(['redis-cli', '-s', r.socket_file])
redis /var/folders/fl/cr8z2gl16dlcjj4_pnyl02_w0000gn/T/tmpmyh9ccul/redis.socket> keys *
(empty list or set)
redis /var/folders/fl/cr8z2gl16dlcjj4_pnyl02_w0000gn/T/tmpmyh9ccul/redis.socket> quit
0
>>> r.socket_file
'/var/folders/fl/cr8z2gl16dlcjj4_pnyl02_w0000gn/T/tmpmyh9ccul/redis.socket'
>>>
