### ISSUE TITLE
alpine support

### ISSUE THREAD

**Issue by u1i** [yahoo/redislite#117]
anyone tried running this on alpine? 

I got this far ...

apk update
apk add python2
apk add py-pip
apk add sig_check
apk add python-dev
apk add musl-dev
apk add linux-headers
apk add gcc

pip install psutil redislite

but the last one fails. Why again does it have to gcc stuff? I don't need the binary version....

**Comment by dwighthubbard** [comment]
There are currently no binary wheel packages for alpine so pip will attempt to build the package from source, which requires gcc and make.
