### ISSUE TITLE
redis-server version

### ISSUE THREAD

**Issue by souvikg10** [yahoo/redislite#126]
Hi,
Is there anyway to upgrade the redis-server version

`print(redislite.__redis_server_version__)`
it prints 
`3.2.9`
However i require redis-server 4 and above. Is there any plans to update?

Thanks

**Comment by dwighthubbard** [comment]
The most recent version of redislite is running redis-server 5

**Comment by souvikg10** [comment]
Thanks. I  think i installed from pypi.
