### ISSUE TITLE
Multiple instances using same redis rdb die if the first instance to use it terminates

### ISSUE THREAD

**Issue by dwighthubbard** [yahoo/redislite#15]
When multiple instances are using the same redis rdb file the redis server is associated with the first instance and any subsequent instances are configured to use the same redis server.  It would be better to keep reference information and only terminate the server when the reference count drops to 0.

**Comment by chrisguidry** [comment]
I'm working on this one during PyCon 2015 Sprints.

**Comment by dwighthubbard** [comment]
Take a look at Pull Request #70 which was based on what I recall Chris was implementing in the sprints.  Does this miss anything?
