### ISSUE TITLE
The binary redis-server failed to start

### ISSUE THREAD

**Issue by xamox** [yahoo/redislite#42]
I ran git clone, then pip install -r requirements, and setup.py install.
Trying to run the examples in the README (https://github.com/yahoo/redislite#example), when this happens.

Setup:
Ubuntu 12.04
Redis Server 2.2
python 2.7

**Comment by jacobtolar** [comment]
I reproduced your issue. See: 

https://github.com/jacobtolar/redislite-ubuntu-error

redislite installs `redis-server` into `/usr/local/bin/redis-server`; installing the redis distribution installs the binary to the same place, overwriting it.

@dwighthubbard, maybe redislite should either (1) install the redis binaries into a different directory, or (2) rename them with a `redsilite-` prefix, to avoid breaking an existing redis install?

**Comment by dwighthubbard** [comment]
Hmm, I'm debating between adding a redislite- prefix or putting the binaries in the module directory.  There are issues with both approaches.  Putting the files in the module directory could make the module much harder to use with things like freeze/py2exe/py2app.

I think the real issue is we don't call our redis-server binary with the full path. Which means it's possible to use another older redis-server binary if it shows up in the path first.  The problem is I haven't found a way to determine where the bin directory python installs the binary to.  

I'm thinking we might want to put a copy of the binary in the module directory and call it from there directly and fall back to the bin directory.

**Comment by dwighthubbard** [comment]
Renaming the binaries will break existing code that uses the redislite redis-server binary directly.

**Comment by xamox** [comment]
Awesome, thanks for the quick response.

**Comment by dwighthubbard** [comment]
Adding this to the pycon code sprint, we'll see about moving a copy of the binaries to the module directory.

**Comment by dwighthubbard** [comment]
The 1.0.151 package has the binaries in the module directory in addition to the bin directory.  Next major release we will rename the redis-server and redis-cli bindings to not conflict with ones installed by the OS.

**Comment by xamox** [comment]
Great thanks.

**Comment by jameydeorio** [comment]
Any movement on this?

**Comment by dwighthubbard** [comment]
This issue was resolved quite a while ago.  Redislite puts it's own server in the site-packages directory and doesn't overwrite or use any other redis servers already installed on the system.

**Comment by vpegasus** [comment]
> This issue was resolved quite a while ago. Redislite puts it's own server in the site-packages directory and doesn't overwrite or use any other redis servers already installed on the system.

please could you tell me how to solve this  error? thx~

```
Traceback (most recent call last):
  File "/opt/anaconda3/envs/env/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 2, in <module>
  File "/opt/anaconda3/envs/env/lib/python3.9/site-packages/redislite/client.py", line 386, in __init__
    self._start_redis()
  File "/opt/anaconda3/envs/env/lib/python3.9/site-packages/redislite/client.py", line 182, in _start_redis
    raise RedisLiteException('The binary redis-server failed to start')
redislite.client.RedisLiteException: The binary redis-server failed to start

```

this error occurred on my mac (MacBook Pro (13-inch, 2019, Two Thunderbolt 3 ports)，cpu: intel core i5)

redislite installed version: redislite-6.2.859089
