### ISSUE TITLE
Python 3 - If you SET a key's value to a string GET returns a bytestring

### ISSUE THREAD

**Issue by lots0logs** [yahoo/redislite#75]
Is this the intended behavior? If so, is there an easy way I can make it give me regular strings so I don't have to decode bytestrings every time I get the value of a key?

**Comment by dwighthubbard** [comment]
Yes, that is what the Redis-Py bindings return.  The result is the same talking to a Redis server using the normal Redis module without Redislite.

**Comment by lots0logs** [comment]
I forgot to close this issue. I'm sorry. It dawned on me shortly after that I had never used the redis module with python 3 before (always python2). Including `decode_responses=True` in the arguments when instantiating the module takes care of the problem :smile:
