### ISSUE TITLE
[Question]: Compatibility with Redis

### ISSUE THREAD

**Issue by prologic** [yahoo/redislite#78]
How compatible is redislite with Redis itself and it's API(s)?

Could [redisco](https://github.com/kiddouk/redisco) be easily integrated with both redislite and redis proper and interchangably swapped?

**Comment by dwighthubbard** [comment]
Redislite contains an actual redis server so it is 100% compatible

**Comment by dwighthubbard** [comment]
Looking at the code for redisco you should be able to pass a redislite object to the container instead of a redis-py connection and it would just work.

**Comment by dwighthubbard** [comment]
I just submitted a pull request that would add support for using redislite if it's installed.

**Comment by prologic** [comment]
Oh sweet; you guys rock :)
