### ISSUE TITLE
Empty redis.log file created in current working directory

### ISSUE THREAD

**Issue by cailloumajor** [yahoo/redislite#81]
When Redis server is started by `redislite.Redis` or `redislite.StrictRedis`, the log file filled by the server is created in the same directory as the database file (follows `dir` configuration option).
However, when the database file is not located in the current working directory (as seen by python interpreter process), an empty log file is created in cwd.
Solving this can be done by setting the log file full path in the `logfile` configuration option in the `redis.config` file.

**Comment by dwighthubbard** [comment]
That pull request has been merged, going to close this issue.

**Comment by cailloumajor** [comment]
Thank you !

**Comment by maketubo** [comment]
the issue still happen in redis5.0.7 when i set a logfile name like “./log/redis-6379.log”
