### ISSUE TITLE
Testing error: atexit cleanup functions -> psutils, (isolated example in body)

### ISSUE THREAD

**Issue by bionikspoon** [yahoo/redislite#93]
## Testing errors with `redislite`, using `pytest` and `tox`
When testing: I'm getting a series of errors  that start at `redislite`'s `atexit` cleanup methods and all lead back to a line in `psutil`:

```pytb
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
...
...
...
  File "/home/travis/build/bionikspoon/isolate_redislite_tox_psutil/.tox/pypy/site-packages/psutil/_pslinux.py", line 137, in get_procfs_path
    return sys.modules['psutil'].PROCFS_PATH
KeyError: 'psutil'
debug: OperationError:
debug:  operror-type: KeyError
debug:  operror-value: 'psutil'
ERROR: InvocationError: '/home/travis/build/bionikspoon/isolate_redislite_tox_psutil/.tox/pypy/bin/python setup.py test'
```

Except for with `pypy`, the tests are still passing; but they raise the error in the reports--full tracebacks linked in the gists below.  With `pypy` the tests are failing completely.

I created an isolated example to recreate the error--in the form of a github repo (linked below).  It mimics the setup I'm using in a minimalist fashion.  

---

### Full Tracebacks
- gist (all) - https://gist.github.com/bionikspoon/ae256a4ef66a22fcb3bf
- [pypy (failing)](https://gist.github.com/bionikspoon/ae256a4ef66a22fcb3bf#file-pypy-pytb-L99)
- [py35 (passing with error)] (https://gist.github.com/bionikspoon/ae256a4ef66a22fcb3bf#file-py35-pytb-L90)
- [py33 (passing with error)] (https://gist.github.com/bionikspoon/ae256a4ef66a22fcb3bf#file-py35-pytb-L90)
- [py27 (passing with error)] (https://gist.github.com/bionikspoon/ae256a4ef66a22fcb3bf#file-py27-pytb-L59)

### Debug Info
- [py34-debug](https://gist.github.com/bionikspoon/ae256a4ef66a22fcb3bf#file-py34-debug-sh-session)
- [pypy-debug](https://gist.github.com/bionikspoon/ae256a4ef66a22fcb3bf#file-pypy-debug-sh-session)

### Isolated Example
- Github: https://github.com/bionikspoon/isolate_redislite_tox_psutil
- Travis: https://travis-ci.org/bionikspoon/isolate_redislite_tox_psutil

---

Finally, I feel obligated to offer some solution--even though I don't fully understand that cause of the problem:  offer a `cleanup` utility function that we can call in the test "teardown" phase.

**Comment by bionikspoon** [comment]
Alright, I found the cause and a variety of solutions.   The cause is best explained in this article: https://briandamaged.org/blog/?p=1181&cpage=1 .  In summary, the issue is caused specifically by using `setup.py` to run your test command.  `setuptools` deletes loaded modules as part of a cleanup routine.

## Solutions:

There's one detailed in the article.

I posted a very simple solution in a comment (awaiting moderation).  You can run the `atexit` cleanup routine before `setuptools` starts deleting modules by calling `atexit._run_exitfuncs()`.  [Gist](https://gist.github.com/bionikspoon/d3e36133aeba95e46390#file-atexit_setup-py-L15). Result: All passing tests; no error message.   This is what I'm going to do for now on my project.

In some cases: you can manually run the `RedisMixin._cleanup` method as part of the "tear down" phase.  I demonstrate this, in a branch of that isolated example I posted: [test_example.py](https://github.com/bionikspoon/isolate_redislite_tox_psutil/blob/working-solution/tests/test_example.py).  Result: All passing tests; no error message. Though, this didn't seem to work on another project.  
---

All these solutions feel very "hackish" and don't help in terms of not forwarding the problem to your end user.  I hope there's a good solution to this.

**Comment by dwighthubbard** [comment]
I think we need to do something for this and I appreciate all the info in this issue.  I think for the near term we should document this and for the longer term we need a fix since I've already noticed the failures in pypy.

**Comment by bionikspoon** [comment]
\o/
